# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 09:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(height_field=100, upload_to='logos', width_field=100)),
                ('title', models.CharField(max_length=128)),
                ('info', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='phone number must be in format +77771112233', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
