# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
