# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-28 09:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20170927_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='address',
            field=models.CharField(max_length=128, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='info',
            field=models.CharField(max_length=128, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='logo',
            field=models.ImageField(upload_to='logos', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='phone number must be in format +77771112233', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
    ]
