# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 03:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0003_auto_20170928_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='title')),
                ('sub_header', models.CharField(max_length=256, verbose_name='sub_header')),
                ('required_sum', models.IntegerField(verbose_name='required sum')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('video', models.URLField(blank=True, max_length=256, null=True, verbose_name='video')),
                ('bg_photo', models.ImageField(upload_to='', verbose_name='image')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Fund', verbose_name='fund')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64, verbose_name='header')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='text')),
                ('list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32, null=True), size=16)),
                ('accent', models.TextField(blank=True, null=True, verbose_name='accent')),
                ('text_after_item', models.TextField(blank=True, null=True, verbose_name='text')),
                ('type', models.CharField(blank=True, choices=[('carousel', 'carousel'), ('slide', 'slide'), ('video', 'video')], max_length=8, null=True, verbose_name='type')),
                ('video', models.URLField(blank=True, max_length=256, null=True, verbose_name='video')),
                ('order', models.PositiveIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='case')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.ContentItem', verbose_name='content item')),
            ],
        ),
    ]
